import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";

function Card() {

  return (
    <div className="flex flex-row gap-2 rounded-lg border aspect-video">
      <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Ace_of_spades.svg/530px-Ace_of_spades.svg.png" className="object-contain h-auto max-w-full rounded-lg"/>
      <div>
        <p>Era:</p>
        <p>Black</p>
        <p>Type:</p>
        <p>Spades</p>
        <p>Name:</p>
        <p>Ace</p>
      </div>
    </div>
  )
}

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="grid grid-cols-2 p-5 gap-4 md:grid-cols-6 md:p-16">
          {
            Array(100).fill(0).map((i: number) => <Card key={i}/>)
          }
        </div>
      </main>
    </>
  );
}
